<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <AnalysisLevel>latest</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>

    <!-- Force UTF-8 -->
    <OutputEncoding>UTF-8</OutputEncoding>
    <CodePage>65001</CodePage>
    <CompilerGeneratedFilesOutputPath>
      $(IntermediateOutputPath)GeneratedFiles
    </CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Backend\CaseConversionAPI\DotNetAPI\DotNetAPI.csproj" />
  </ItemGroup>

  <!-- Windows native library -->
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <Content Include="$(MSBuildProjectDirectory)\..\..\CppLib\build\**\libProcessStringDLL.dll">
      <Link>libProcessStringDLL.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <!-- Linux native library -->
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <Content Include="$(MSBuildProjectDirectory)\..\..\CppLib\build\**\libProcessStringDLL.so">
      <Link>libProcessStringDLL.so</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <!-- macOS native library -->
  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <Content Include="$(MSBuildProjectDirectory)\..\..\CppLib\build\**\libProcessStringDLL.dylib">
      <Link>libProcessStringDLL.dylib</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <!-- Audited warnings -->
    <NoWarn>$(NoWarn);NU1902;CS8625</NoWarn>
  </PropertyGroup>

</Project>